# Generated by Django 3.0.5 on 2020-04-20 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thoughts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbackinfo',
            options={'verbose_name_plural': 'Feedback Info'},
        ),
    ]
