# Generated by Django 3.0.5 on 2020-04-21 22:47

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("thoughts", "0003_auto_20200421_2158"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True)),
                ("post_text", models.TextField(blank=True, null=True)),
                ("message", models.TextField(blank=True, null=True)),
                ("number", models.IntegerField(blank=True, null=True)),
            ],
            options={"verbose_name_plural": "Feedback Info",},
        ),
        migrations.AlterField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post",
                to="thoughts.Feedback",
            ),
        ),
        migrations.DeleteModel(name="FeedbackInfo",),
    ]
