# Generated by Django 3.0.5 on 2020-04-23 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("thoughts", "0004_auto_20200421_2247"),
    ]

    operations = [
        migrations.DeleteModel(name="Comment",),
        migrations.DeleteModel(name="Feedback",),
        migrations.DeleteModel(name="User",),
    ]
