# Generated by Django 3.0.5 on 2020-04-26 18:49

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("thoughts", "0007_auto_20200423_2154"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                default="-1",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coments",
                to="thoughts.Comment",
            ),
        ),
    ]
