# Generated by Django 3.0.5 on 2020-04-26 19:03

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("thoughts", "0008_auto_20200426_1849"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="parent",
            field=models.ForeignKey(
                default="-1",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coments",
                to="thoughts.Comment",
            ),
        ),
    ]
