# Generated by Django 3.0.5 on 2020-04-26 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("thoughts", "0010_auto_20200426_1914"),
    ]

    operations = [
        migrations.DeleteModel(name="Comment",),
        migrations.DeleteModel(name="Post",),
        migrations.DeleteModel(name="User",),
    ]
