# Generated by Django 3.0.6 on 2020-05-10 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("thoughts", "0014_comment"),
    ]

    operations = [
        migrations.DeleteModel(name="Comment",),
        migrations.DeleteModel(name="Post",),
        migrations.DeleteModel(name="User",),
    ]
