dist: xenial
language: python

services:
  - postgresql

env:
  global:
    - ENV_FOR_DYNACONF=travis
    - SD_DATABASE_URL="postgresql://postgres@localhost:5432/tmssite"

install:
  - pip install pipenv --upgrade
  - make venv static

before_script:
  - make resetdb

script:
  - make test

after_success:
  - codecov

cache: pip

jobs:
  include:
    - stage: test
      python: '3.6.9'