service: g
provider:
  name: aws
  runtime: python3.6
  timeout: 60
  versionFunctions: false
  endpointType: REGIONAL
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:ListBucket'
      Resource:
        - 'arn:aws:s3:::phototomypage/*'
    - Effect: 'Allow'
      Action:
        - 's3:PutObject'
      Resource:
        - 'arn:aws:s3:::phototomypage/*'
functions:
  resizer:
    environment:
      PYTHONPATH: src
    handler: src.resizer.lambda_function.lambda_handler
    events:
      - s3:
          bucket: phototomypage
          event: s3:ObjectCreated:*
          existing: true
plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: non-linux