# Generated by Django 3.0.7 on 2020-06-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_photo_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sending_tg',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
