# Generated by Django 3.0.5 on 2020-04-23 00:29

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0003_project_firm"),
    ]

    operations = [
        migrations.CreateModel(
            name="Firm",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={"ordering": ("name",),},
        ),
        migrations.CreateModel(
            name="PPProject",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True)),
                ("started_at", models.DateField(blank=True, null=True)),
                ("finished_at", models.DateField(blank=True, null=True)),
                ("summary", models.TextField(blank=True, null=True)),
                ("achievements", models.TextField(blank=True, null=True)),
                ("responsibilities", models.TextField(blank=True, null=True)),
                (
                    "firm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="resume.Firm",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Projects",
                "ordering": ("-started_at", "name"),
            },
        ),
        migrations.RemoveField(model_name="responsibility", name="project",),
        migrations.AlterModelOptions(
            name="technology",
            options={"ordering": ("name",), "verbose_name_plural": "Technologies"},
        ),
        migrations.AddField(
            model_name="technology",
            name="version",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(name="Project",),
        migrations.DeleteModel(name="Responsibility",),
        migrations.AddField(
            model_name="ppproject",
            name="technologies",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to="resume.Technology"
            ),
        ),
    ]
