# Generated by Django 3.0.5 on 2020-04-23 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0004_auto_20200423_0029"),
    ]

    operations = [
        migrations.RemoveField(model_name="ppproject", name="achievements",),
        migrations.RemoveField(model_name="ppproject", name="responsibilities",),
    ]
