# Generated by Django 3.0.5 on 2020-04-23 08:07

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0005_auto_20200423_0145"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True)),
                ("started_at", models.DateField(blank=True, null=True)),
                ("finished_at", models.DateField(blank=True, null=True)),
                ("summary", models.TextField(blank=True, null=True)),
                (
                    "firm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="resume.Firm",
                    ),
                ),
                (
                    "technologies",
                    models.ManyToManyField(
                        blank=True, related_name="projects", to="resume.Technology"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Projects",
                "ordering": ("-started_at", "name"),
            },
        ),
        migrations.DeleteModel(name="PPProject",),
    ]
