# Generated by Django 3.0.5 on 2020-04-23 08:17

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0006_auto_20200423_0807"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="achievements",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="responsibilities",
            field=models.TextField(blank=True, null=True),
        ),
    ]
